### ISSUE TITLE
Compilation issues on Windows with maven

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline-cli-go#26]
When trying to build the cli project from this repo or from the [main pipeline](github.com/daisy/pipeline) repo on windows, i noticed several issues :
- the maven project relies heavily on make and could be replaced by maven calls
- the yaml dependencie failed to download from launchpad and should be replaced by its [newer repo](https://github.com/go-yaml/yaml)
- With the latest version of the repo, an int to string conversion error is raised from utils.go (an explicit conversion of a minJavaVersion to string is required)

I also noticed tests issues, where unix path (like '/tmp/') are used.

**Comment by NPavie** [comment]
In linux and windows, the job_mapper tests are failing with the following log :
```
2019/06/11 11:54:52 open /tmp/go-build826376204/b001/config.yml: no such file or directory
/tmp/go-build826376204/b001
path /home/cosa/pipeline2
fatal error: concurrent map writes

goroutine 121 [running]:
runtime.throw(0x87d3ce, 0x15)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81 fp=0xc420249d38 sp=0xc420249d18 pc=0x42caf1
runtime.mapassign_faststr(0x803fc0, 0xc4202155f0, 0x87581f, 0x1, 0x42e86e)
	/usr/lib/go-1.10/src/runtime/hashmap_fast.go:703 +0x3e9 fp=0xc420249da8 sp=0xc420249d38 pc=0x40d7d9
github.com/daisy/pipeline-cli-go/cli.TestMap.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	[..]/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/job_mapper_test.go:76 +0x50 fp=0xc420249de0 sp=0xc420249da8 pc=0x794590
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420249de8 sp=0xc420249de0 pc=0x45b411
created by github.com/daisy/pipeline-cli-go/cli.parallelMap
	[..]/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/job_mapper.go:18 +0x1ee

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420202f00, 0x877084, 0x7, 0x894e50, 0x47d201)
	/usr/lib/go-1.10/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc420158000)
	/usr/lib/go-1.10/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc420158000, 0xc42013dd90)
	/usr/lib/go-1.10/src/testing/testing.go:777 +0xd0
testing.runTests(0xc420112540, 0xac2280, 0x7f, 0x7f, 0x411e59)
	/usr/lib/go-1.10/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc42012e280, 0x0)
	/usr/lib/go-1.10/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:358 +0x208

goroutine 120 [runnable]:
github.com/daisy/pipeline-cli-go/cli.parallelMap(0xc4200659b0, 0x3, 0x3, 0xc420217600, 0x895050, 0x0, 0x0, 0x0)
	[..]/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/job_mapper.go:25 +0x2ac
github.com/daisy/pipeline-cli-go/cli.TestMap(0xc420202f00)
	[..]/pipeline-cli-go/build/src/github.com/daisy/pipeline-cli-go/cli/job_mapper_test.go:80 +0x139
testing.tRunner(0xc420202f00, 0x894e50)
	/usr/lib/go-1.10/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/lib/go-1.10/src/testing/testing.go:824 +0x2e0
FAIL	github.com/daisy/pipeline-cli-go/cli	0.010s
```

**Comment by bertfrees** [comment]
This happens every now and then. I don't know what is causing it.
